server:
  port: ${PORT:8089}
  servlet:
    context-path: /cargo

spring:
  application:
    name: study-jpa
  profiles:
    active: ${PROFILE:dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME:alura.study-jpa}
    username: ${DB_USER:study}
    password: ${DB_PASS:123}

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    servlet:
      path: /v1
